### ISSUE TITLE
Search 函数缺少单测

### ISSUE THREAD

**Issue by ericuni** [issue9/cnregion#3]
```golang
cn, err := data.Embed("|", 2021)
assert.Nil(err)

got := cn.Search(&cnregion.SearchOptions{Text: "温州"})
```
got 是空的.

PS: 加入了Embed 可以再发布一个版本出来, `go get github.com/issue9/cnregion` 得到的版本是不带有Embed 函数的版本

**Comment by caixw** [comment]
Embed 现在在 data 之下，引用之后应该就有了。
Search 我回头试试看。

**Comment by ericuni** [comment]
需要显示的指定master 业绩是`go get github.com/issue9/cnregion@master` 才能拉取到包含Embed 函数的版本.
另外, 建议把Embed 函数也放在cnregion 这个pkg 下, 对外暴漏的主入口函数放一起.

**Comment by caixw** [comment]
Embed 暂时不会移至根目录，不想造成 Embed 滥用，还是希望用户独立读取的方式使用数据，这样方便后期更新数据库，也不会造成二进制文件过大。

**Comment by caixw** [comment]
v1.2021.1 可以正常使用 data.Embed
