### ISSUE TITLE
是不是tjj服务端有流量检测了？等一会就context deadline exceeded 

### ISSUE THREAD

**Issue by zzti** [issue9/cnregion#4]
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/42/01/03/420103010.html
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/42/01/03/420103013.html
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/42/01/03/420103006.html
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/42/01/03/420103400.html
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/42/01/03/420103012.html
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/42/01/03/420103401.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/42/10/88/421088103.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/42/10/88/421088103.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/36/07/31/360731205.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/36/07/31/360731205.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/13/11/27/131127105.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/13/11/27/131127105.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/13/11/25/131125401.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/13/11/25/131125401.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/32/05/07/320507006.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/32/05/07/320507006.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/32/05/05/320505408.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/32/05/05/320505408.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/32/04/02/320402003.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/32/04/02/320402003.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/41/15/28/411528205.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/41/15/28/411528205.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/41/14/02/411402007.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/41/14/02/411402007.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/51/33/26/513326214.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/51/33/26/513326214.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/51/17/25/511725121.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0
抓取 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/51/17/25/511725121.html
ERROR: Get "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/21/01/15/210115111.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 并返回状态码 0

**Comment by caixw** [comment]
是的
